### ISSUE TITLE
gulp-util is marked as dev-only dependency

### ISSUE THREAD

**Issue by laufhannes** [mikeerickson/gulp-phpunit#42]
Trying to include `gulp-phpunit` (i.e. nothing more than `var phpunit = require('gulp-phpunit');`) fails because `gulp-util` can't be found:
```
$ gulp
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (./node_modules/gulp-phpunit/index.js:12:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Moving `gulp-util` from `devDependencies` to `dependencies` should solve this issue.

**Comment by mikeerickson** [comment]
@laufhannes Thanks for notice, I will get this cured shortly.

**Comment by mikeerickson** [comment]
@laufhannes This has been cured in 0.15.1, my apologies for mixup.  Surprised this just appeared now, it has been like this since very early in development :-)
